---
- name: Fetch Latest ServiceNow Incident and Update to In Progress
  hosts: localhost
  gather_facts: no

  vars:
    snow_instance: "nowlearning-nlinst04482238-7y7gv-0001.lab.service-now.com"
    snow_username: "admin"
    snow_password: "4J5eGjXBpx8Z"

  tasks:
  
    - name: Update Incident to In Progress
      uri:
        url: "https://{{ snow_instance }}/api/now/table/incident/{{ incident_sys_id }}"
        method: PATCH
        user: "{{ snow_username }}"
        password: "{{ snow_password }}"
        force_basic_auth: yes
        validate_certs: no
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          state: "2"
          work_notes: "Investigation started by Ansible Automation Platform."
        status_code: 200
      register: update_result

    - name: Save Incident Details for Next Workflow
      copy:
        dest: /tmp/incident_details.json
        content: |
          {
            "sys_id": "{{ incident_sys_id }}",
            "number": "{{ incident_number }}"
          }

    - name: Display Updated Incident Details
      debug:
        msg:
          - "Incident Updated Successfully"
          - "Incident Number : {{ incident_number }}"
          - "Incident Sys ID : {{ incident_sys_id }}"
          - "State Updated To : In Progress"

    - name: Pass incident details to next workflow node
      set_stats:
        data:
          incident_sys_id: "{{ incident_sys_id }}"
          incident_number: "{{ incident_number }}"
